### ISSUE TITLE
Can you consider adding a function "show sprite"?

### ISSUE THREAD

**Issue by 1130381752** [TASVideos/fceux#107]
I want rip sprite's animation, but some games the role A is very close to role B, but I want to rip both the two sprites. If the emulator can show each sprite or not individually, I can rip them very easy. Can you help me?

**Comment by g0me3** [comment]
if you need to rip the sprite, first figure out the sprite format then write the rip tool. the emulator cannot rip sprites for you.

**Comment by bbbradsmith** [comment]
Config > Display > Graphics: OBJ / Graphics: BG might help? If you turn off BG (background) only the sprites are left (OBJ) which are easy to screenshot.

**Comment by 1130381752** [comment]
Thank you, but when the two sprites are overlap, I can't rip them individually.

**Comment by bbbradsmith** [comment]
If the sprites don't ever display in the game without being overlapped, are they really separate sprites?

Otherwise, what you could maybe do is identify the CHR tiles involved in the overlapping sprite, the go to the hex editor and replace its tile with 16 bytes of 0.

...but really if you're asking for an emulator to un-layer sprites for you, you're probably not going to find one that will do this. There's no way for an emulator to know anything about which tiles belong together and which don't. That's all at the game software level, not the emulator.

**Comment by 1130381752** [comment]
I 'm learning nes rom hacking, maybe I can use CHR to transparent the specific sprite
