### ISSUE TITLE
Test ROM causes FCEUX to crash

### ISSUE THREAD

**Issue by sdeken** [TASVideos/fceux#109]
Attached is a test ROM with a bad header (byte 8 of the header is misplaced) that is causing FCEUX to crash at various times. Sometimes it crashes immediately upon boot; other times it crashes when attempting to show the hex editor or debugger, otherwise it crashes upon exit.

The program is very simple - it just reads the controller and writes some values to zero page if the directional buttons are held on Controller 1. It also configures the MMC3 and copies data from the PRG-ROM to PPU memory and enables rendering.

Due to the misplaced byte, the header is claiming that the cart has 8KB of PRG-RAM (it should have none) and 256 bytes of CHR-RAM (it should have 8KB). This does not appear to be so wrong that it should cause FCEUX to crash.

The crash appears to be caused by attempting to write more bytes to CHR-RAM than are available; the program copies 8KB of data from PRG-ROM to CHR-RAM, and if this is omitted the crash no longer occurs. Oddly, this can be avoided by pausing FCEUX, loading the ROM, and displaying the hex editor / debugger prior to unpausing - although FCUEX still crashes on exit.

[nes-game.zip](https://github.com/TASVideos/fceux/files/4552117/nes-game.zip)

**Comment by negativeExponent** [comment]
why would you call it "misplaced"? as far as nes 2.0 is a concern, this is a valid header. Its not correct for rom though.

**Comment by bbbradsmith** [comment]
"Misplaced" was from the perspective of sdeken trying to write the intended header for the ROM.

Anyhow, a CHR-RAM of 256 bytes is too small to handle, apparently. The problem is VPage only being able to work with 1k banks. The memory corruption will happen at ppu.cpp line 966 when it attempts to write off the end of the 256 byte memory, which eventually causes a crash when the program realizes memory has been corrupted, possibly during free(VROM), but can happen elsewhere depending on the corruption.

So, I'd suggest the current best solution is to throw an error when using CHR-RAM size < 1024 instead of loading the cartridge. I don't know if there's any value in trying to support lower sizes, but that's probably good enough until something exists that actually needs that.

Related: not sure if necessary but CHRmask1/2/4/8 can end up with -1 if CHR-RAM is < 8k. Might suggest inserting the following to disable banking for sizes that can't handle it instead? Not sure.

```
	if (CHRmask1[chip] >= (unsigned int)(-1)) CHRmask1[chip] = 0;
	if (CHRmask2[chip] >= (unsigned int)(-1)) CHRmask2[chip] = 0;
	if (CHRmask4[chip] >= (unsigned int)(-1)) CHRmask4[chip] = 0;
	if (CHRmask8[chip] >= (unsigned int)(-1)) CHRmask8[chip] = 0;
```

**Comment by bbbradsmith** [comment]
So, created a fix, which just disallows the ROM, but the reported error is an unsupported mapper. Would be nice if that error could be improved, but I don't see a good place to deliver that at the moment.

**Comment by bbbradsmith** [comment]
iNES_Init was called in only one place, so adding an error report was apparently not that hard.
