### ISSUE TITLE
Inputs Not Working In Games

### ISSUE THREAD

**Issue by SloppyPancake66** [TASVideos/fceux#138]
I can set up inputs in the controller config window, but no inputs will register in the games.  I have tried redownloading and clearing inputs.  they even work on a different emulator. Could anyone help?

Linux Mint 20 Cinnamon ver. 4.6.6

**Comment by mjbudd77** [comment]
I can help you, but I will need more information. What port are you trying to configure and what type of input device are you using? Can you attach a screen shot of the game pad configure window after mapping all the buttons? What version of sdl2 are you using? Running fceux with a --help argument should give you all the version information for the linked dependencies.

**Comment by SloppyPancake66** [comment]
Explain what you mean by 'port' and 'input device' I am running SDL version 2.0.10. Attached is a screenshot of the finished button mapping.
![gamepad](https://user-images.githubusercontent.com/68626417/88131092-056dcd80-cb91-11ea-8e39-1a6590bebb1a.png)

**Comment by SloppyPancake66** [comment]
In this image, I have Snes9x open, running Donkey Kong Country.  As you can see, all of the inputs I was pressing registered. these being 'A' 'B' 'Select' and 'Start'.  This is just as a proof that my controllers do work.  ![Screenshot from 2020-07-21 21-00-49](https://user-images.githubusercontent.com/68626417/88132982-ca21cd80-cb95-11ea-94c9-c2ee80c9d89a.png)

**Comment by mjbudd77** [comment]
I don't doubt that the physical game pad is working. It would have never seen button presses to map to otherwise. I don't see anything glaringly wrong from the image. If you close the game pad window and re-open it, are the settings still the same as before closing It? Just want to make sure the mappings saved properly.  Also, just as a sanity check, if you load the default keyboard mappings from the load defaults button. Will the game respond to those keyboard inputs? If you had a previous fceux.cfg file in $HOME/.fceux can you try removing that and then restart the application? This will allow the application to generate a new config file with default values. The configuration values have changed a bit and I want to ensure there are no improper old configs messing it up.

**Comment by SloppyPancake66** [comment]
The values change only after completely closing the emulator.  the files attached show how these values change.  The default keyboard mapping do work as intended.  I can also remap to anywhere on the keyboard or mouse and it works just fine.  Looking through my config files, I can not find a previous version of the application
![gamepad-before](https://user-images.githubusercontent.com/68626417/88134525-b4aea280-cb99-11ea-8ddd-648c90841449.png)
![gamepad-after](https://user-images.githubusercontent.com/68626417/88134532-b710fc80-cb99-11ea-811f-8b05f1693cfd.png)

**Comment by mjbudd77** [comment]
At the moment, im out of ideas. Sorry, its past midnight and im having trouble thinking straight. I will try to reproduce this tomorrow. On a side note,  I noticed the original image had the device ID of js13. Do you have 13 joysticks plugged in at once? I don't think I've ever tested with more than 2. I will do some tests to try and determine why the values didn't save properly. One last question, each time you re did the mappings, was the device ID and button/axis numbering consistent between each calibration?

**Comment by SloppyPancake66** [comment]
I only have one joystick plugged in.  It may be because I have multiple peripherals, but I don't think my motherboard even supports 13 usb ports.  The mappings were consistent every time I re-mapped the buttons.  Out of 20 times, only once did the IDs not match the listed numbers.  The order was "0, 2, 4, 6, 8, 10, 12, 14".

**Comment by mjbudd77** [comment]
I just pushed some new game pad input configuration updates to master for the Qt/SDL port. You will see that the game pad config window has changed a bit. I added a configuration profile interface to save the game pad button mappings to a named profile for the given device type. While digging through this code, I did find a few variables that could potentially be uninitialized depending on how the application starts up. I have fixed these which may have been your issue. Also, I added button state feedback so that button presses for current active mapping can be visually verified. The pick off point for this feedback signal is where the button state is tested and packed into the variable used by the core of the emulation. So, if the feedback indications turn from red to green when you are pressing the buttons, then I'm pretty confident that the emulator is seeing those button states. Anyway, pull the latest code from master and let me know if things are any better.

**Comment by mjbudd77** [comment]
I went one step further and created a Linux mint virtual machine to try to replicate your exact issue. The latest build had no problem with using game pads in this environment.

**Comment by SloppyPancake66** [comment]
It may have been an issue with my packages and how I installed them.  Thank you for helping.  I will get back to this thread when I have fixed the problem.  I have very little experience on linux but Mint is close enough to Windows that I should be able to navigate relatively easily.

**Comment by SloppyPancake66** [comment]
Whatever you did fixed the issue I had.  I was never able to find the cause of it.  The new build with the indicators is very helpful, thank you.
