### ISSUE TITLE
Close Fceux closes system session

### ISSUE THREAD

**Issue by Amnesia1000** [TASVideos/fceux#147]
When I close Fceux, it closes the system session.

Own compilation, Manjaro Gnome.

Build configuration:
base CPPDEFINES: ['PUBLIC_RELEASE', '_SDL2', '_REENTRANT', '_GTK3', '_S9XLUA_H', 'PSS_STYLE = 1', 'FCEUDEF_DEBUGGER', 'LSB_FIRST', 'FRAMESKIP']
CCFLAGS base: ['-Wall', '-Wno-write-strings',' -Wno-sign-compare ',' -Wno-parentheses', '-Wno-unused-local-typedefs',' -DBACKWARD_HAS_DW = 1 ',' -DHAVE_ASPRINTF ',' -pthread ',' -D_GTK ',' -DLUA_USE_LINUX ',' -Isrc / lua / src ',' -DOPENGL ']

Steps to compile.
git clone https://github.com/TASVideos/fceux
cd fceux
scons RELEASE=1 GTK3=1 GTK=0

I have also tried cmake with these parameters:
cmake -DCMAKE_BUILD_TYPE=Release ..
which makes the session not close, but it is based on Qt5 not gtk3.

I have tested the installable versions from the Manjaro package manager (pamac) and the versions that can be installed are fceux (official repositories, version GTK3, also close the session), fceux-gtk3-git (repositories AUR, GTK3, also close the session) and fceux-git (AUR repositories, GTK3, also close the session).

At first I thought that some configuration to compile conflicts with gnome, but apparently the gtk3 version has some incompatibility with gnome 3.36 (or Manjaro/Arch).

Characteristics of the PC in case it is relevant.
Manjaro Linux; Build ID: rolling
OS type: 64 bit
Gnome version: 3.36.4
Window system: X11
Processor: AMD® Ryzen 5 3600 6-core processor × 12
Memory: 23.5 GiB
Graphics: GeForce GTX 1060 6GB / PCIe / SSE2

**Comment by Amnesia1000** [comment]
I just opened the emulator, and deactivated "Enable OpenGL" and when closing the emulator the session was not closed, the problem is in OpenGL that for some reason closes the system session when closing the emulator.

**Comment by mjbudd77** [comment]
I looked at the code and, based on your description of the issue, decided to change the quit logic so that the GTK GUI can perform an orderly exit of its main loop and then shutdown outside of the GTK event loop. I have merged this change into the master branch. Hopefully it helps fix the issue. Let me know how it goes. That said, I have decided to discontinue development of the GTK GUI in favor of the new Qt5 GUI that I have put together. I decided to make this move to overcome some cross platform issues I was having between Linux and MacOSX. Also, after working with Qt, I have found that it is much easier to work with and seems performs better than GTK. So since, I would prefer to move forward with Qt... Is there a reason you don't want to give the Qt GUI a try? It should be able to do everything the GTK GUI can do (minus a few debug tools that I'm still in the process of coding).

**Comment by Amnesia1000** [comment]
To be honest I don't have a valid reason to use only the GTK version, I prefer it because it uses Gnome and the truth is that the aesthetics it has are amazing and I prefer to use GTK-based applications.

In the current state, Fceux is fully functional in GTK so I will continue using this version (if the use of OpenGL has been solved).

If you think that the way to go is Qt and that the emulator can improve more in the Qt environment than in GTK, you could start using the Qt version, although you would still use GTK until the difference between versions (improvements or features) is really noticeable .

**Comment by mjbudd77** [comment]
The main problem I have is that I cannot recreate your issue. I also run a gnome desktop (version 3.32), but on a Centos 8 Linux distro which tends to lag behind the latest cutting edge software package releases, is more stable as a result. This desktop crash has never occurred for me. I have one last idea, I will try to create a virtual machine with the exact distro you have and see what happens when buildIng and running the program. Just so I understand, you are able to start the program, load and play games with OpenGL, and then when you try to close the application it logs you out of the desktop session? Or crashes?

**Comment by Amnesia1000** [comment]
It is exactly as you say, the games run well on the emulator with OpenGL activated, the problem is that closing the emulator closes the session (it does not have any other type of error, be it a crash or a sign with an error)

What I do is play with OpenGL activated, save, close the game and deactivate OpenGL to be able to close the emulator quietly, but sometimes I forget to deactivate it and when I close fceux the session closes ...

The problem with logging out is that I can't provide you with some kind of log.

**Comment by mjbudd77** [comment]
Just merged another change into master that I would like you to try. There are 3 ways to close the GUI, window close button (usually on upper right corner), main menu File -> Quit option, and Ctrl + Q key sequence when the window has focus. Please try all 3.

**Comment by Amnesia1000** [comment]
I tried all 3 methods, and with the new compilation the session does not close when I close the emulator, now the problem is that after closing the emulator, if I reopen it, the session closes ...

**Comment by mjbudd77** [comment]
I created a Manjaro VM this morning and built and tested the latest fceux. Other than some annoying scons build issues and was able to start/stop the application and run games with no issues. No gnome crashes occurred. All version information you mentioned above is the same except my VM is not using Nvidia graphics. It shows  llvmpipe (LLVM 10.0.0, 256 bits) for my graphics. My actual graphics hardware on the host machine is  Intel HD Graphics 530 (Skylake GT2). So based on this, my guess is that there is some bug / incompatibility between the Nvidia OpenGL implementation and the GTK3/GLX/X11 libraries. Sorry to say that I think this problem is outside of my control. I have looked at the code over and over and cannot find anything else that would be suspect. I googled manjaro gnome crashes got some hits on NVidia gnome issues. Some users tried switching from the proprietary Nvidia driver to the open-source nouveau driver. If you wish to debug this further, check your X11 logs for crash information or maybe see if a newer Nvidia driver is available. Could also try a different linux distro, I am also curious, does the glxgears program run fine on your computer? Might be another good test. Or.... you could just run with the Qt5 version of fceux... maybe it will grow on you. :)

**Comment by Amnesia1000** [comment]
The craziest thing just happened to me. After trying yesterday's new compilation, with the above mentioned error, I turned off the PC. Today I turn it on again and it didn't log in (I have to log in automatically, without asking for user or password), then I realized that it's not that it didn't log in, but that it automatically logged in and out.

I could only log in by entering the console (Ctrl+Alt+F2) and then returning to the graphical version (Ctrl+Alt+F1). Once I logged in, I restarted the PC to see if it had been fixed completely, but no, the same problem came back, so I did the same to be able to log in, I started FCEUX (which had OpenGL enabled), disabled OpenGL, closed the emulator (so it would take the changes), restarted the PC and the error was gone.

I just read your last comment, no problem, for now there is no noticeable difference in using OpenGL and not using it. For merely aesthetic reasons I'll use FCEUX GTK3 with OpenGL disabled. 

If you discontinue GTK3, and there are many differences between the old GTK3 version I own and the new Qt versions, I will upgrade and change to Qt, but for now I think this bug has already taken too much time. I hope that the emulator will advance enough to be able to pass me and enjoy new features.

Yesterday I created a Feature Request for the emulator portability, when that is possible it will be final my change (if only this is possible in Qt) since I have all my games and emulators in a portable disk that I always carry with me.

Thank you very much for the time dedicated to this problem.

**Comment by mjbudd77** [comment]
Closing issue as it appears to be bug in low level graphics/desktop code and not in fceux.

**Comment by mjbudd77** [comment]
FYI, my most recent updates have added a third video option. The three video options are OpenGL GLX, SDL, and Cairo. SDL is the new driver. The cairo driver is not very efficient, so may want to give the SDL option a try. Hope it helps.

**Comment by Amnesia1000** [comment]
Thanks
