### ISSUE TITLE
FCEUX-gtk not maintain option SDL

### ISSUE THREAD

**Issue by Amnesia1000** [TASVideos/fceux#157]
When SLD is put in the video options (Linux GTK version), and the emulator is closed, when it is reopened it shows OPENGL (GX) again.

I opened the configuration file ./fceus/fceux.cfg and it shows SDL.OpenGL = 1, manually change the option to 0, reopened the emulator and shows OPENGL again, I looked at the fceux.cfg file and it changed alone to SDL. OpenGL = 1.

Every time the emulator is opened it changes the video to OPENGL

**Comment by Amnesia1000** [comment]
Fixed with the latest Git update.

**Comment by mjbudd77** [comment]
Looks like you have it working, but wanted to let you know that the SDL.OpenGL option has been removed from the code. The code now uses SDL.VideoDriver which can have the following values for the GTK GUI:   0=OpenGL (GLX),  1=SDL,  2=Cairo. Just curious, did this help you previous issue at all?

**Comment by Amnesia1000** [comment]
Yes, this help

**Comment by Amnesia1000** [comment]
> Looks like you have it working, but wanted to let you know that the SDL.OpenGL option has been removed from the code. The code now uses SDL.VideoDriver which can have the following values for the GTK GUI: 0=OpenGL (GLX), 1=SDL, 2=Cairo. Just curious, did this help you previous issue at all?

Well, here is an update of what is happening with the gtk version.

The gtk/nvidia/OpenGL problem persists (I can confirm that it stops only with nvidia boards, or the current drivers), the OpenGL (GX) option is no longer always by default, but the login problem continues.
After the update that changed the way to close the emulator, the session did not close when closing the emulator, but closed when opening it a second time.
The problem with this is that the PC does not start session if you do not enter terminal mode (Ctrl + Alt + F2) and then back to graphics mode (Ctrl + Alt + F1).
The only way to fix the problem is to delete the gtk binary, delete the configuration file, open the qt binary and configure it.
Then when restarting the PC, it starts the user normally.

**Comment by mjbudd77** [comment]
I've learned that some linux systems have to versions of OpenGL libraries installed. Legacy and GL Vendor Neutral (GLVND). I changed the cmake build setup so that you can specify whether you want to build the Qt or GTK version of the GUI. Please don't use the scons to build anymore. I hate supporting it and cmake is much more reliable system to system. I would like you the GTK GUI in this way using GLVND, from the root directory of the project:
`mkdir buildGTK; cd buildGTK;`
`cmake -DGTK=1 -DGLVND=1 ..` 
If you get the same behavior with that build, try building again with the legacy OpenGL being linked:
`cmake -DGTK=1  ..` 
I'm hoping that using one or the other GL library will have better results, not sure which one the scons build was using.

**Comment by Amnesia1000** [comment]
Okay, I'll try it in a little while. I haven't used scons to compile in a few days now.

**Comment by Amnesia1000** [comment]
Well, I just compiled the 2 versions of OpenGL and the same thing keeps happening.
