### ISSUE TITLE
macOS app bundles have missing dependencies

### ISSUE THREAD

**Issue by brianlheim** [TASVideos/fceux#212]
the app bundle in the prebuilt macOS dmg files only contains the fceux executable, but it depends on non-system shared libraries

```
[brianheim@BrianMBP MacOS]$ otool -L fceux
fceux:
	/usr/local/opt/qt/lib/QtOpenGL.framework/Versions/5/QtOpenGL (compatibility version 5.15.0, current version 5.15.1)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/local/opt/minizip/lib/libminizip.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.15.0, current version 5.15.1)
	/usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.15.0, current version 5.15.1)
	/usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.15.0, current version 5.15.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

an app bundle should contain all the shared libraries it needs that may not be present on the user's system. it is a requirement for signed and notarized app bundles, too. anyone running fceux on a system that doesn't already have these libraries will see the app fail to start with no indication why (this happened to me).

since it looks like the project uses Qt, there's a tool that comes with Qt called `macdeployqt` that can help with this. there's also fixup_bundle in this CMake module: https://cmake.org/cmake/help/latest/module/BundleUtilities.html

**Comment by mjbudd77** [comment]
The macOS bundle is compiled against homebrew installed packages. They need to be installed as documented on the fceux web page. See link below.
http://fceux.com/web/osx.html
These packages must be installed via home brew:
brew install qt5
brew install sdl2
brew install minizip

**Comment by brianlheim** [comment]
i understand, but the dependencies should really be in the app bundle, this is standard for macOS distribution and would save people time and confusion. plus, if you ever want to sign the app, you'll have to do it anyway.

**Comment by brianlheim** [comment]
would you accept a patch which does this?

**Comment by mjbudd77** [comment]
I understand.  But the homebrew packages are not built to be in the bundle. I tried and the bundle packaging tools rejected it.  Also, I do not have full control of the appveyor build environment to where I can install the necessary Qt5 and SDL2 dmg bundles.

**Comment by mjbudd77** [comment]
Really, if the appveyor environment had all the necessary installed packages built properly for bundling, then I would not have had use home brew in the first place. Maybe it is as simple as contacting appveyor support and asking them to add these dependencies to the virtual environment, I never tried because the home brew seemed to work fine. But you are right that we are not bundling this correctly. If you know of a better way, I appreciate the help.

**Comment by brianlheim** [comment]
@mjbudd77 ok! i've opened a PR here: #213. i don't think using homebrew is a problem, and explained in more detail over there.

you mentioned SDL2 dependencies; i've never worked with SDL2 before, does the app require anything besides the single SDL2 dylib?

**Comment by mjbudd77** [comment]
Thank you for the help! I installed the bundle and checked the executable and could see that it was linking the libraries coming from the bundle. I believe SDL2 only has the one dylib file. The best way to check is to also uninstall the home brew sdl2 and see if the app still runs. But I suspect that it will work since otool is showing that the bundled libs are being found. I have never really given much thought about getting the app signed and I'm not really sure what that process entails. When I am finally ready to make a new release of this software, I will research how all that works. Thank you again.

**Comment by brianlheim** [comment]
> I believe SDL2 only has the one dylib file. The best way to check is to also uninstall the home brew sdl2 and see if the app still runs.

i tested it this way and it started also, so i think it's good.

> Thank you again.

happy to help!
