### ISSUE TITLE
[Request] Option to take uncompressed screenshots.

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/fceux#241]
Right now, when a screenshot is taken, it's saved in .png format. If I try to edit the image to add different colors, it won't allow those colors. It only allows whatever colors the image is already using. To get around that, I have to convert the image to a 24-bit color .bmp and then back to .png so it has the full range of colors.

I assume this is because the png is compressed? If that's the case, could there be a toggle to take uncompressed images for editing purposes? 

Thanks!

**Comment by bbbradsmith** [comment]
What you're describing should not have anything to do with compression, but if a PNG used a palette for its colours that might happen, depending on how your editor handles palettes.

However, FCEUX outputs 24-bpp PNGs as far as I can tell, no palettes, so I'm not sure why this would be happening to you.

**Comment by mjbudd77** [comment]
I'm not really seeing how it is really worth changing the current behavior for this. Programs like GIMP can change the format of an image in a few mouse clicks. Seems like a lot of work to fix a small inconvenience.

**Comment by ReyVGM** [comment]
Thanks for the reply, but please close this issue. 

I noticed that I was using fceux-2.2.2, which has the behavior I described. I tried version 2.2.3 and that problem is no longer present. So whatever it was, someone fixed it in that last version!

**Comment by Yave-Yu** [comment]
Technically this is not compressed, but made color palette in index (256 colors) like GIF.

**Comment by bbbradsmith** [comment]
Though most NES images have far fewer colours, the rendering interface has to support 512 (all emphasis combinations), which wouldn't fit in an indexed PNG. Maybe it'd be nice if it could encode the 64 colour palette in an indexed PNG when there is no emphasis, but I can't really think of a good justification for needing this.

If you're just asking for compression's sake, though, I think you'll find that the size difference between an indexed 8-bit PNG and a 24-bit png is negligible due to its existing compression methods.
