### ISSUE TITLE
workaround for systems without __THROWNL (src/lua-engine.cpp)

### ISSUE THREAD

**Issue by libTorrentUser** [TASVideos/fceux#246]
I tried to build the latest master on an Alpine Linux machine and the compilation fails due to `__THROWNL` being undefined inside [src/lua-engine.cpp](https://github.com/TASVideos/fceux/blob/521846cf976eb6a12729e2238bec3800ceebb017/src/lua-engine.cpp#L198) 

Simply defining it to the same thing glibc does is enough to make the code compile. So I suggest changing the first few lines to

    #ifdef __linux
    #include <stdlib.h>
    #include <unistd.h>
    #define SetCurrentDir chdir
    #include <sys/types.h>
    #include <sys/wait.h>
    #include <libgen.h>
    
    #ifndef __THROWNL
    #define __THROWNL throw ()
    #endif

    #elif   __APPLE__

And just another thing. I think you should change `pkg_check_modules( LUA lua-5.1)` [CMakeLists.txt](https://github.com/TASVideos/fceux/blob/521846cf976eb6a12729e2238bec3800ceebb017/src/CMakeLists.txt#L88) to `pkg_check_modules( LUA lua=5.1)`, or maybe even  `pkg_check_modules( LUA lua>=5.1)` (if you are feeling brave). My system likes to name the library `lua5.1`. Because reasons. And because of that, the current code does not detect it.

**Comment by mjbudd77** [comment]
Just curious, will adding this line fix the build issue:
```
#include <stdio.h>
```
As for Lua, if the system 5.1 lua cannot be found, it will just internally link the 5.1 lua anyways. I'm hesitant to move to a later Lua because I have read that major changes have been made in Lua 5.3 and am unsure how those will affect others at this time.

**Comment by libTorrentUser** [comment]
Just tested. Unfortunately, no. Same error. I guess it is because that macro is more a glib thing and some systems, like Alpine, don't use it. Alpine uses musl libc, if I am not mistaken, and that means a bunch of non-standard stuff glib defines won't be available.

Fortunately, that one seems to be the only one in the whole code :)

As for the lua issue, I understand your hesitation (I think you talked about it in another issue), so we can scratch using newer versions for now. But I still believe you should change the check to `pkg_check_modules( LUA lua=5.1)`, because it would still be the same check, only more robust, since it would also work on systems where the library is named `lua5.1` instead of `lua-5.1` (notice the lack of hyphen).

That, of course, assuming the change does not break the build on systems where the lib has the hyphen :)

**Comment by mjbudd77** [comment]
Just merged the proposed build fix into the master branch. Please confirm that it works. 
I looked into the lua cmake issue and your proposed fix for that did not work well on my computer. My computer is running linux CentOS8 and has two lua packages installed: lua  (version 5.3)  and lua-5.1  (version 5.1.4). So in my case, in order to properly link the system lua-5.1 library the line needs to read:
```
pkg_check_modules( LUA lua-5.1 )
```
I did try a different approach that I think will work for the both of us. I changed that line to this:
```
pkg_search_module( LUA lua5.1 lua-5.1 )
```
This will cause cmake to search for packages of both names and use the first one it finds. In my testing, it is working well for me.

**Comment by libTorrentUser** [comment]
Just tested. Installed lua 5.1 (5.1.5 on Alpine) and then performed a clean build. CMake found the lib and the code compiled without issues. 

Awesome!
