### ISSUE TITLE
Requesting wram usage with mapper 209

### ISSUE THREAD

**Issue by therealinfidelity** [TASVideos/fceux#38]
I don't know how to write in c++, and I wanted to know if there is a way to have a modified version of mapper 209, to allow for wram usage? $D000's leftmost bit allows you to use $6000-$7FFF as ROM if the bit is set, but I would like to use it as WRAM/SRAM with that bit as 0. If I knew how to accomplish this on my own I would, this is the only feature I wish would work. I'm not looking to make/create repro carts, I simply want to use this for emulation. Thank you.

**Comment by zeromus** [comment]
why? 

I might could give it to you as long as you're ok with having it be battery backed. that's because this is something that could conceivably break a mapper 209 game (if it expects open bus and receives wram instead) but no such game would set the battery bit in the iNES header. If YOU set that bit, then I could give you the ram.

or I could tell you how to hack it for your personal private purposes.

**Comment by therealinfidelity** [comment]
I have projects that I wish to use this mapper for, but I want to be able to save progress within those projects. If I can do this for my own personal use, then I'd appreciate any guidance to accomplish that. I'm not out to have a mapper broken, but the wiki does say to have the leftmost bit of $D000 not set, on order to use PRG-RAM. If I misinterpreted the description then that's on me. With all of that said, I would really appreciate to be able to modify 209 for my projects.

**Comment by zeromus** [comment]
I read the wiki and I didn't see that. The only reference to PRG-RAM on the wiki suggests you should change it to use mapper 35 and presto you will have wram

**Comment by therealinfidelity** [comment]
Yeah I've tried 35, but it lacks some of what 209's registers use. Like $8003 doesn't work, so I cant swap out either c000-fff, or e000-ffff. If I could be guided on what mapper file to edit (I forget off the top of my head) to allow wram in 209, that would be great. I'm sorry for misreading the wiki, I swore it said "prg-ram map here, if not, open bus"

**Comment by zeromus** [comment]
if nesdev wiki says "35 is 209 with wram" and fceux's 35 is anything other than "209 with wram" then post a bug saying "fceux's 35 is wrong"... and...... assign it........... to the guy....................... who already.................................. oh.

@g0me3  - the original nesdev wiki docs on 35 from year 2014 say 
"FCEUX's source says mapper 35 represents Wario Land 2 (Famicom) - a pirate ROM hack of Kirby's Adventure. That implementation looks an ''awful'' lot like mapper 90"

Can you find out which of these is the case
1. FCEUX mapper 35 has been the same since 2009: it works your way, and nesdev is mistaken in thinking it's like 209
2. FCEUX mapper 35 was changed from a mapper 90 clone by YOU to your own mapper 35, sometime after 2014

If it's 1., then I'll edit the wiki to say "no, it's actually different" and try and figure out why myself
If it's 2., then I'll edit the wiki to say "no, it's actually different. see FCEUX sources for reference; we don't need redundant mapper 35 and I am revoking it to use for dumps made in 2009 with an actually really different board"

**Comment by therealinfidelity** [comment]
I'd still like to stick with using 209, and I always under the impression that any nes game could have access to 6000-7FFF, so this has been a learning experience these past few days. I'm still open to using a modified version of 209 with wram.

**Comment by zeromus** [comment]
Sorry, you don't get to be to choose. We have to make sure this gets done right. I explained why a mapper that can't support wram shouldnt have wram support added, when i mentioned that it should only happen if it's battery backed.

**Comment by therealinfidelity** [comment]
But you said earlier I could for personal use? I'll just ditch the idea entirely.

**Comment by zeromus** [comment]
well, you can do whatever you want for personal use. it's probably trivial to fix for personal use.

**Comment by therealinfidelity** [comment]
For me it wouldn't be trivial, but I don't know how to write c, if I did then I would modify the source myself for personal use. But since I don't know c, I cant move forward with my ideas. So I'll just scrap the ideas I had, I misinterpreted the wiki for 209, and 35 is not a duplicate of 209 with sram. So I'll just move on. Thanks again for the replies.

**Comment by zeromus** [comment]
It's trivial for me to tell you how to do it. If you care so little that youre already moving on I won't bother

**Comment by therealinfidelity** [comment]
I've been led to care little due to a variety of circumstances from various people, from various sites. All I asked for was the ability to use wram with a specific mapper, and my request has been going in circles for days now, with me not reaching the outcome I desire. Ive read documents and did various rom tests with multiple mappers from the 209 family, before reaching out to whomever could shed light and give assistance. I've read documents that were misleading and had to be updated (nesdev did so from my findings) and I've been trying to simply have a feature which (I thought was universal which is on me) is supposed to work on all games, since the wram is part of the nes. Then you tell me ko it shouldn't be done with 209, but will let me know how to do it for personal use only, since you don't want the mapper set up incorrectly, which I understand. And then when I take you on the offer to have help in having 209 modified for personal use, I'm told "I don't get to be choosy" so yes that deters me from trying to reach my goal. I'm not an experienced developer, if I knew c/c++, then I'd do it all myself. So I'm just going to move on from this since it wont be resolved for my personal use. Again I appreciate you taking the time to go back and forth on this, thank you.

**Comment by zeromus** [comment]
The WRAM isn't part of the NES.
It would be resolved for your personal use if I told you how.
But whatever.
