### ISSUE TITLE
Support for Translation 

### ISSUE THREAD

**Issue by L1cardo** [TASVideos/fceux#4]
I want to translate fceux into Chinese , but I don't know how to do .

**Comment by bbbradsmith** [comment]
I don't think there's an easy answer to this question.

A lot of the user interface text is contained in [src/drivers/win/res.rc](https://github.com/TASVideos/fceux/blob/master/src/drivers/win/res.rc) but there is a whole lot more scattered throughout the code. The SDL version might have a completely separate set of text too.

I don't think there's really a practical way to make this into an application with a language setting that can switch languages, it would probably be much easier to create a separate fork for a Chinese build.

**Comment by L1cardo** [comment]
ok，  thank you

**Comment by L1cardo** [comment]
hahaha，the code is scattered throughout the code，it would be a huge work for me.

**Comment by movsb** [comment]
FCEUX的代码确实很混乱，很久以前我翻译过SVN版本的。
但是由于我非常不喜欢SVN，加上FCEUX迟迟没有使用GIT，我就没有再维护了。代码也不知哪里去了。

**Comment by L1cardo** [comment]
我也觉得这个版本汉化太难了，我现在在着手于汉化Mesen。作者在首页也推荐了Mesen，试用了以后觉得体验也很好，汉化起来也挺方便的。

**Comment by movsb** [comment]
我接触FCEUX的代码有7、8年了，有点不舍😜。

**Comment by L1cardo** [comment]
哈哈，我只是一个菜鸟，对编程感兴趣，但是知道的不多，源代码编译成程序我都不会😂，只能做做汉化，然后给作者，让他们加入到程序中 哈哈

**Comment by movsb** [comment]
FCEUX的代码其实非常不规范，写得非常散乱。
而且FCEUX是从很多个不同的FCU分支版本合并而来的，所以更加搞乱了代码。
而且他们的代码压根没有考虑过语言问题，所以要翻译很难。
翻译是个长期活，需要一直同步维护。开始之前要想好。😃

**Comment by L1cardo** [comment]
哈哈，这个我知道的，要一直维护版本，我现在也在参与[Playnite的汉化](https://github.com/JosefNemec/Playnite/issues/299)，你可以看看，也可以提出适当的建议。

**Comment by owomomo** [comment]
我说楼上几位，你们不知道FCEUX好多年前就有汉化版了么？Mesen也已经有人汉化过了。
For the people above, don't you know that FCEUX has been translated to Chinese many years ago? By the way, Mesen is also translated now.

**Comment by L1cardo** [comment]
可以把汉化的人地址放出来吗？谢谢

**Comment by owomomo** [comment]
用中文谷歌随便一搜就能搜出来。
我惊讶的是都汉化了这么多年了，居然还有人不知道有中文版。

**Comment by L1cardo** [comment]
麻烦可以把地址给我吗？我搜不到，或者搜到了都是很早的版本，没有新版本

**Comment by owomomo** [comment]
2.2.3就是最后一个正式版了，如果这个还算早，你是想要最近的Git版还是怎么的？

**Comment by bbbradsmith** [comment]
> For the people above, don't you know that FCEUX has been translated to Chinese many years ago? By the way, Mesen is also translated now.
If the source for this translation is available (which it should be, because of the license), you might consider starting a fork here now that FCEUX is here on github, and transferring that translation work to it, so that it can be easily updated in the future.

You might also contact the maintainers of the website so that a link to it might be placed on the downloads page, so people who come to it in the future might have a better chance of finding the translation.
http://www.fceux.com/web/download.html

**Comment by movsb** [comment]
@owomomo Can you please tell us where the source code is? Or, Is it source-opened? Is it updated to the main repo?

**Comment by SourMesen** [comment]
@owomomo AFAIK, the Chinese translation of Mesen that exists is in violation of GPL (no source release), and if at all possible, I would rather have a proper Chinese translation of Mesen available (e.g by someone who actually contributes the translation to the code, rather than releasing their own Chinese-only binary-only release.)

**Comment by L1cardo** [comment]
@SourMesen  I am working on the Chinese translation of Mesen,  but it will take some time due to I have to prepare for my exams these days .

**Comment by movsb** [comment]
@SourMesen HHH, Chinese developers usually don't care what license you're using. Shame on that.

**Comment by SourMesen** [comment]
@L1cardo No worries, take your time.  Good luck on your exams!

@movsb Can't be helped, the simplest solution is to offer a better alternative :)

**Comment by owomomo** [comment]
I don't have the Chinese localized code of FCEUX, and tried to contact the author of Chinese FCEUX but no respond yet, since I don't have too much connet to him now (I know my Github account has some same information but it may take too long to explain why).
The unauthorized translation or modifying code is quite common in China, not only FCEUX, but also many others, they usually don't care about this because there are so many developers doing this in their country. Because of the gap of languages, the original author even don't know their code has been localized to Chinese for years.
The only thing I can do is to try to connect him and request him to open the source, but this is only when he responds me, that's sad.
