### ISSUE TITLE
The "sav" file for one ROM is being saved under wrong name if you open another ROM file

### ISSUE THREAD

**Issue by pvanukoff** [TASVideos/fceux#43]
Environment: Windows 10 x64

Steps to reproduce:

1. Clear any existing files in the sav folder.
2. Launch FCEUX.
3. Open Legend of Zelda (may happen with other games, this just what I saw it on).
4. Open any other ROM file. 

In the sav folder, a sav file (for LoZ) will be created under the name of the ROM from step 4. 

The next time you load the game from step 3, it won't be able to locate the correct sav for that game because it was saved under the wrong filename. 

I see this issue happens on build 0.0.0.116 (and later) but not on 0.0.0.115.

**Comment by pvanukoff** [comment]
If I close the running game before loading a new one, the sav file is saved correctly. This leads be to think this issue could have something to do with line 1073 being commented out of /src/drivers/win/window.cpp:

// if (GameInfo) FCEUI_CloseGame();

**Comment by owomomo** [comment]
The problem is that the previous game was closed too late after some variable has changed to the newer one.
I commented out the close game function because the current game was closed even if the newly loaded game was failed before actually start loading. If it has no affection to the old one, so why interrupt it.
But what I didn't realized is that some of the data outside has already change before the reset game function call. I changed the reset function call prior, you can test if it works fine.

**Comment by g0me3** [comment]
works fine for me in current version. should we close issue?

**Comment by pvanukoff** [comment]
I hadn't had time to confirm. Thank you!
