### ISSUE TITLE
64-bit (x64) builds for 64-bit Wine

### ISSUE THREAD

**Issue by pinobatch** [TASVideos/fceux#57]
If you've heard of the [Catalina Wine Mixer](https://www.visitcatalinaisland.com/catalina-wine-mixer/), macOS 10.15 is the [Catalina Wine Killer](https://www.amion.com/cgi-bin/ocs?Page=Help:151).

macOS 10.15, due for release in September or October, will drop multiarch and instead run only 64-bit executables. As I understand it, Wine on a 64-bit-only system can run only those Windows executables that are compiled for x64 (x86-64, AMD64), not x86. How hard would it be to build FCEUX (debugging version) for 64-bit Windows? Or will it become recommended to debug games running in FCEUX SDL by debugging FCEUX SDL itself?

**Comment by bbbradsmith** [comment]
There's an x64 configuration in the Visual Studio project. It builds and runs just fine.

**Comment by pinobatch** [comment]
If you can slip me a test build, I'll test what I can in 64-bit Wine on Xubuntu. And if that works, I'll keep an eye out for Mac users who might be interested. (I myself don't use a Mac, but I'm in Discord servers with people who do.)

**Comment by movsb** [comment]
> And if that works, I'll keep an eye out for Mac users who might be interested.

How I'd love to run FCEUX on macOS, but I find it so hard to make it. And its SDL2 branch is behind master for hundreds of commits.

Once upon a time, I was thinking about rewriting its UI the HTML way. 🤣

**Comment by bbbradsmith** [comment]
VC x64 build from current master:
[fceux_x64_7047a99.zip](https://github.com/TASVideos/fceux/files/3287580/fceux_x64_7047a99.zip)

**Comment by pinobatch** [comment]
Thanks. The 64-bit build worked on Ubuntu; I'll ask my Mac-using friends to try it and report back.

**Comment by pinobatch** [comment]
I don't think that build is actually 64-bit
```
$ file /path/to/fceux.exe
/path/to/fceux.exe: PE32 executable (GUI) Intel 80386, for MS Windows
$ file /path/to/mptrack.exe 
/path/to/mptrack.exe: PE32+ executable (GUI) x86-64, for MS Windows
```
I'll read the AppVeyor docs as I get time.

**Comment by movsb** [comment]
![QQ20190616-115735](https://user-images.githubusercontent.com/5374525/59558834-f7fd2000-902d-11e9-8fc8-f34e42fd9f63.png)

Yes, it's a 32bit executable.

**Comment by bbbradsmith** [comment]
My apologies. I assumed the configuration labelled "x64" was a 64 bit build, but apparently the actual setting for that configuration was still Win32. Switching its platform setting to actually be x64, it no longer compiles.

**Comment by pinobatch** [comment]
Ubuntu will soon drop support for 32-bit libraries as well according to ["I386 architecture will be dropped starting with eoan (Ubuntu 19.10)" by willcooke](https://discourse.ubuntu.com/t/i386-architecture-will-be-dropped-starting-with-eoan-ubuntu-19-10/11263), via ["Wine Developers Concerned With Ubuntu Dropping 32-bit Support With Ubuntu 19.10" by Logix](https://www.linuxuprising.com/2019/06/wine-developers-concerned-with-ubuntu.html), via [Slashdot](https://linux.slashdot.org/story/19/06/21/1359225/wine-developers-concerned-with-ubuntu-dropping-32-bit-support-with-ubuntu-1910). This means that one of five things will end up happening:

- A. Somebody figures out what causes FCEUX debugger to fail to compile under x64.
- B. Somebody creates, publishes, and maintains a snap that contains FCEUX debugger, Wine, and the 32-bit "core18" runtime.
- C. Following ["Running Steam in a LXD system container" by Simos Xenitellis](https://blog.simos.info/running-steam-in-a-lxd-system-container/), somebody experiments with LXD containers to figure out what is and isn't needed to run FCEUX debugger in Wine in Ubuntu 18.04 LTS in a container in a more recent version of Ubuntu and then publishes a guide to doing so.
- D. Somebody prepares and publishes a guide on how to debug NES programs in FCEUX by debugging FCEUX SDL itself using GDB.
- E. FCEUX debugger users switch _en masse_ to Mesen, and macOS users end up installing Xubuntu in a VM to run Mesen.

**Comment by bbbradsmith** [comment]
I started [a branch on my fork](https://github.com/bbbradsmith/fceux/tree/win64_attempt) to see how far I could get with setting up a 64 bit build.

With #62 to update a bunch of incompatible 32-bit Windows API usage I can get it to completely compile. I can't quite link because of #63 luaperks.lib, which I don't yet know the source of, but I think once a 64-bit version of that library can be found, it should link?

There's a _lot_ of compiler warnings that should be investigated for 32-bit truncation. I'm definitely not expecting it to run without a bunch more work.

Also a lot of "windows" stuff is predicated on the WIN32 define, so I have it defining WIN32 on the WIN64 build as well. That should eventually be sorted out, but for this first pass the "WIN32" define basically has to mean both Win32 and x64.

There's also a reliance on very old DirectX 8 libraries. These are actually included in the github source tree. I managed to track down the last published version of the relevant libraries (dinput was the bottleneck), and luckily they did have 64 bit libs for them at the time (2007).

**Comment by bbbradsmith** [comment]
Alright, after Feos showed me where to find luaperks, I managed to get it to link and run! I still need to do a big pass over all the new warnings, but it looks at least minimally viable now! (See: [bbbradsmith/fceux/win64_attempt](https://github.com/bbbradsmith/fceux/tree/win64_attempt))

**Comment by bbbradsmith** [comment]
Hooked my fork up to appveyor in case anyone wants to try it. I'm still working on it, but it's already in a runnable state, it seems.

https://ci.appveyor.com/project/bbbradsmith/fceux/build/artifacts

**Comment by vadosnaprimer** [comment]
I'd consider ability to run on 64bit Unix-like (Wine or not) a nice reason to make a new release.

**Comment by bbbradsmith** [comment]
So there are 64-bit LIB/DLL for Lua already in the repo. I needed to make a 64-bit build of the LuaPerks from  [tastools](https://github.com/TASVideos/tastools/tree/master/Lua/LuaPerks), which compiles and links fine, but the program just exits if I actually try to run a Lua script.

In FCEU_LoadLuaCode it gets as far as [**iplua_open**](https://github.com/bbbradsmith/fceux/blob/f992836d3a46c7987b42717c94044eeee8ebfb84/src/lua-engine.cpp#L6077), which goes into LuaPerks and eventually gets to **iuplua_register_cb** where it calls [**lua_call**](https://github.com/TASVideos/tastools/blob/f8730cdbbdceec7df868ecdbe10ae7b7684e293f/Lua/LuaPerks/iup3.0-rc3/srclua5/iuplua.c#L387) (which now goes into the DLL) and the program exists with error code 1. That's as far as I got in debugging.

I tried a few different permutations of build settings for luaperks, different versions of lua 5.1.x, etc., but so far haven't come up with anything that works. I think the next step is to build lua from source to get a version with debug symbols and keep drilling into this with the debugger but I think this is the point where I just put Lua on a to-do list and forget about it indefinitely.

Otherwise I still haven't found any other problems in testing yet. I gotta try out more of the tools. I'm also still in the process of reviewing the enormous warning log from the build to see if there is anything suspicious.

**Comment by bbbradsmith** [comment]
Lua [now seems to be working](https://github.com/bbbradsmith/fceux/commit/bf3bb9ff2f660e07814f24549207e7866613667e), I just had to produce some missing generated 64-bit precompiled lua stuff for LuaPerks.

**Comment by bbbradsmith** [comment]
The first pass on that seems to be fully functional at this point. There's a build here if anyone wants to test:
https://ci.appveyor.com/project/bbbradsmith/fceux/build/artifacts

**Comment by pinobatch** [comment]
This EXE is indeed for x86-64, and it's working in wine-3.6 (Ubuntu 3.6-1). I'll pass this one to Mac-using friends.

**Comment by pinobatch** [comment]
I had kmck from the NESdev and FamiTracker servers try an AppVeyor build on Wine 4.0.1 under macOS 10.14.5 "Mojave". At first, with a 32-bit prefix, this error happened:
```
$ WINEPREFIX=~/.wine-fceux-32 wine ~/Wine/fceux_x64/fceux.exe 
wine: Bad EXE format for Z:\Users\keith\Wine\fceux_x64\fceux.exe.
```
Minutes later: "Runs fine with a 64-bit prefix. Cursory poking at debug tools seems normal. All in all, my verdict is working as expected in Wine."

**Comment by bbbradsmith** [comment]
The changes in #66 have now been merged into the main branch. I will be deleting the fork branch I tested it in, but I will leave its appveyor artifact up until it expires.

If someone wants to create their own 64-bit build with appveyor, the settings I used are attached in this appveyor.yml file.

[appveyor.yml.txt](https://github.com/TASVideos/fceux/files/3423757/appveyor.yml.txt)

**Comment by agg23** [comment]
Why was the 64-bit build not added to the main Appveyor artifact drop?

**Comment by bbbradsmith** [comment]
Why wasn't it added? You're the first person who's actually asked for it.

zeromus' appveyor just does the win32 build, not any of the other targets. I dunno if he'd want to add x64 (or SDL/linux etc.) to it, but it's actually pretty easy to set up your own:

Just fork FCEUX to your own user-space, and set up an appveyor project on that. That's what I did when testing this build.

The setup for that is pretty simple. You can look at the YML above, which is very minimal. Other than selecting the configuration it's just a matter of including the 64-bit lua DLLs in the archive step.

**Comment by bbbradsmith** [comment]
Okay with #122 there is now a 64-bit build available in the appveyor.
