### ISSUE TITLE
Mapper 547 (QTai) unsupported

### ISSUE THREAD

**Issue by Loggan08** [TASVideos/fceux#79]
As topic above

**Comment by dragon2snow** [comment]
547 == UNIF KONAMI_QTAI

**Comment by g0me3** [comment]
i hate to do these hacks, but there are some differences between how ines (even 2.0) mapper and unif board do PRG loading and handling and thus to make the same code work with both at the same thime you need add more hacks and comparisons... it is possible but sometimes it need a lot of putting head in ass.

added it here https://github.com/TASVideos/fceux/commit/25c0b96c30d5a43bf3e5dc74abec751b3b9d6d97

also we need to change the way we handle non power2 rom sizes for ines 2.0 currently it also redived from ines 1.0 but since we have 2.0 it is not necessary.
